config/routes.rb
Kmpit::Application.routes.draw do
  scope '/:locale' do
    root 'frontend#index'
    devise_for :users
    
    post :contact_requests, path: "contact-request", controller: :frontend, action: :contact_request
  end

  get '/' => 'frontend#get_locale'
end

app/models/contact_request.rb
class ContactRequest < ActiveRecord::Base
  
  validates :name, :telephone, :email, presence: true
  validates :email, format: /[-0-9a-zA-Z.+_]+@[-0-9a-zA-Z.+_]+\.[a-zA-Z]{2,4}/
  validates :description, presence: true, length: { maximum: 240 }

end

app/models/service.rb
class Service < ActiveRecord::Base
  
  has_one :contact_requests, dependent: :nullify
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  before_action :fetch_rss
  before_action :set_locale
  
  def index
    @contact_request = ContactRequest.new

    if params[:locale]
      if available_languages.include?(params[:locale])
        session[:locale] = params[:locale].to_sym
      else
        get_locale
      end
    end
    I18n.locale = session[:locale] if session[:locale].present?
  end

  def get_locale
    redirect_to "/#{locale}"
  end

  def contact_request
    @contact_request = ContactRequest.new contact_request_params
    #render text: @contact_request.service_names.inspect
    #return
    if @contact_request.save
      FrontendMailer.hire_us_form("mariusz.zak@rst-it.com", "system@kmpit.com", @contact_request).deliver
      flash[:notice] = I18n.t "form_success", scope: "messages"
      redirect_to action: :index
    else
      flash.now[:alert] = I18n.t "form_error", scope: "messages"
      render action: :index
    end
  end
  
  private
    def contact_request_params
      params.require(:contact_request).permit(:name, :telephone, :email, :description)
    end
    
    def extract_locale_from_accept_language_header
      request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first rescue "en"
    end
    
    def fetch_rss
      require 'rss'
      rss = RSS::Parser.parse(open('http://howwedoapps.com/articles.rss').read, false)
      @latest_post = rss.items.first
    rescue
      nil
    end

    def set_locale
      I18n.locale = session[:locale] || extract_locale_from_accept_language_header
      I18n.locale = :en unless available_languages.include?(locale.to_s)
      session[:locale] = locale
    end

    def available_languages
      %w{en de pl}
    end
end

app/helpers/frontend_helper.rb
module FrontendHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end
  
  def main_menu
    %w( home what_we_do our_team blog hire_us contact )
  end
  
  def section_heading section
    html = <<-HTML
      <header class="section-heading">
        <h2>
          #{I18n.t(section, scope: "section_headings")}
          <span class="border"></span>
        </h2>
      </header>
    HTML
    html.html_safe
  end
  
  def technologies
    [
      ["HTML5 / HAML / SLIM","CSS3 / SASS / SCSS","JavaScript","CoffeeScript", "AngularJS", "Backbone.js", "Marionette.js","WEBGL"],
      ["Ruby on Rails", "Node.js", "Express.js", "Websockets", "Objective C","Java"],
      ["REST API","OAuth2","JSON / XML","Google Maps API","Facebook API","Twitter API","Open ID"],
      ["MySQL","PostgreSQL","Amazon (AWS)","NGINX","MongoDB","Prediction.io", "ElasticSearch" ,"Redis","Memcached"]
    ]
  end
  
  def parse_to_img_url text
    text.downcase.gsub(" ","-")
  end
  
  
  # collections used in sections
  
  def web_and_mobile_collection # home section
    [
      "AngularJS",
      "Ruby on Rails",
      "Android",
      "iOS",
      "HTML5",
      "RWD"
    ]
  end
  
  def references_collection # references section
    [
      {name: "Grzegorz Kornak", position: "Director of Infrastructure Division", company: "Asseco Poland", text: t("ref1", scope: "references"), img_url: "/references/01.png"},
      {name: "Katarzyna Dorsey", position: "President at", company: "Yosh", text: t("ref2", scope: "references"), img_url: "/references/02.png"},
      {name: "Małgorzat Stuła", position: "CEO", company: "My Green Space", text: t("ref3", scope: "references"), img_url: "/references/03.png"}
    ]
  end
  
  def facts_collection # fact section
    [
      {number: "102", name: t("number_of_clients", scope: "facts.blocks")},
      {number: "170", name: t("finished_projects", scope: "facts.blocks")},
      {number: "8750", name: t("days_at_work", scope: "facts.blocks")},
      {number: "10<sup>6</sup>", name: t("lines_of_code", scope: "facts.blocks")},
      {number: "9204", name: t("drank_coffee_pots", scope: "facts.blocks")}
    ]
  end
  
  def projects_technologies_collection # selected projects section
    [
      {
        name: "mgs",
        layers: 3,
        technologies: [
          "Ruby on Rails",
          "HTML5",
          "WebGL",
          "Mandrill",
          "Backbone.js",
          "PayPal"
        ]
      },
      {
        name: "taxi5",
        layers: 4,
        technologies: [
          "Ruby on Rails",
          "HTML5",
          "Java",
          "Objective-C",
          ".NET",
          "WebSocket",
          "NodeJS",
          "Redis",
          "Android",
          "iOS",
          "API"
        ]
      },
      {
        name: "mood",
        layers: 3,
        technologies: [
          "Ruby on Rails",
          "Streaming",
          "REST API",
          "Backbone.js"
        ]
      },
      {
        name: "flicolo",
        layers: 5,
        technologies: [
          "Ruby on Rails",
          "HTML5",
          "Backbone.js",
          "OAuth 2",
          "ElasticSearch",
          "RWD", 
          "Android",
          "Redis"
        ]
      }
    ]
  end


end

app/views/frontend/index.html.slim
= render "frontend/sections/home"
= render "frontend/sections/what_we_do"
= render "frontend/sections/our_way"
= render "frontend/sections/our_way_development"
= render "frontend/sections/selected_projects"

= render "frontend/sections/our_team"
= render "frontend/sections/hire_us"
= render "frontend/sections/contact"
= render "frontend/sections/map"

app/views/frontend/sections/_contact.html.slim
section#contact.section-grey.p-b-60
  .row
    == section_heading "contact"
    .blocks.m-t-60
      .block.medium-6.columns
        = image_tag "frontend/sections/contact/krzysztof.png"
        .details
          h5 Krzysztof Marszałek
          p.position Co-founder/CCO
          p.telephone +48 883 957 517
          p.email krzysztof.marszalek@rst-it.com
          a.medium.linkedin href="https://www.linkedin.com/profile/view?id=223961579&goback=%2Enmp_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1_*1&trk=spm_pic" target="_blank"
            .fc-linkedin
      .block.medium-6.columns
        = image_tag "frontend/sections/contact/jolanta.png"
        .details
          h5 Jolanta Żukowska
          p.position Key Account Manager – Köln, Germany
          p.telephone +49 151 21 924029
          p.email jolanta.zukowska@rst-it.com

app/views/frontend/sections/_facts.html.slim
section#facts
  .row.m-b-20
    == section_heading "facts"
    - if facts_collection.present?
      ul class="large-block-grid-#{facts_collection.size}"
        - facts_collection.each do |f|
          li.block
            .number== f[:number]
            .name== f[:name]

app/views/frontend/sections/_hire_us.html.slim
section#hire_us
  .row
    == section_heading "hire_us"
    p== t "hire_us", scope: "section_texts"
    = simple_form_for @contact_request, url: contact_requests_path(anchor: "hire_us")  do |f|
      .m-b-35
        = f.input :name
        = f.input :telephone
        = f.input :email
        = f.input :description, as: :text
      button type="submit"
        == t "send", scope: "buttons"

app/views/frontend/sections/_home.html.slim
section#home.active
  .image-wrapper
  .row
    header.m-b-60
      h2
        small== t "home", scope: "section_headings"
        br
        == t "home1", scope: "section_headings"

app/views/frontend/sections/_map.html.slim
section#map
  .row
    .offices
      .office.clearfix
        h5
          == t "office1_heading", scope: "offices"
          span.border
        = image_tag "frontend/sections/map/offices/office1.jpg"
        .details
          p
            | Wrocławski Park Technologiczny
            br
            | Budynek Gamma
            br
            | Muchoborska 18
            br
            | 54-427 Wroclaw
     
  #googlemap

app/views/frontend/sections/_mission.html.slim
section#mission
  .row
    h4= t "our_mission", scope: "headings"
    == section_heading "mission"

app/views/frontend/sections/_our_team.html.slim
section#our_team.section-light-text.show-for-medium-up
  .video-wrapper
    video autoplay="" loop="" poster="/videos/our-team.jpg"
      source src="/videos/our-team.webm" type="video/webm"
      source src="/videos/our-team.ogv" type="video/ogg"
      source src="/videos/our-team.mp4" type="video/mp4"
    
  .content
    .row
      == section_heading "our_team"
      p== t "our_team", scope: "section_texts"
      .buttons
        a.circle-button.github href="https://github.com/RSTgroup" target="_blank"
          .icon
          .text== t "github", scope: "our_team.buttons"
        a.circle-button.cv href="/files/rst_our_cv.pdf" target="_blank"
          .icon
          .text== t "cv", scope: "our_team.buttons"
        a.circle-button.hire-us.to-section href="#hire_us"
          .icon
          .text== t "hire_us", scope: "our_team.buttons"

app/views/frontend/sections/_our_way.html.slim
section#our_way
  .row
    == section_heading "our_way"
    p== t "our_way", scope: "section_texts"
    .sprint.p-v-70
      = image_tag "frontend/sections/our_way/sprint.png"
      h3.m-t-50== t "sprint", scope: "headings"
    == section_heading "our_rules"
    #rules.p-v-30
      .columns.large-6
        - (1..2).each do |r|
          .rule
            .no= r
            .text= t "rule#{r}", scope: "our_rules"
      .columns.large-6
        - (3..3).each do |r|
          .rule
            .no= r
            .text= t "rule#{r}", scope: "our_rules"

app/views/frontend/sections/_our_way_development.html.slim
section#our_way_development.section-grey    
  .row
    == section_heading "our_way_development"
    p== t "our_way_development", scope: "section_texts"
    .m-t-80.m-b-80= image_tag "frontend/sections/our_way/development.jpg"

app/views/frontend/sections/_selected_projects.html.slim
- if projects_technologies_collection.present? 
  section#selected_projects.section-grey
    .row
      == section_heading "selected_projects"
      .project-name
        - projects_technologies_collection.each_with_index do |project,i|
          .name class="#{project[:name]} #{'active' if i==0}"
            - unless project[:name] == "mood"
              h3
                = t(project[:name], scope: "portfolio.names")
            - else
              = image_tag "frontend/sections/selected_projects/mood/mood-logo.png"
      #carousel
        .wrapper
          - projects_technologies_collection.each_with_index do |project,i|
            .slide class="#{project[:name]} #{'active' if i==0}"
              - project[:layers].times do |l|
                = image_tag "frontend/sections/selected_projects/#{project[:name]}/layer#{l+1}.png", class: "layer layer#{l+1}"
        a.prev.arrow
        a.next.arrow
      .project-description
        - projects_technologies_collection.each_with_index do |project,i|
          .description class="#{project[:name]} #{'active' if i==0}"
            == t project[:name], scope: "portfolio.descriptions"
      .project-technologies
        - projects_technologies_collection.each_with_index do |project,i|
          .technologies class="#{project[:name]} #{'active' if i==0}"
            - if project[:technologies].present?
              - project[:technologies].each do |tech|
                .label== tech

app/views/frontend/sections/_selected_technologies.html.slim
section#selected_technologies.section-grey.show-for-medium-up
  ul.large-block-grid-6
    li= image_tag "frontend/sections/selected_technologies/rails.png"
    li= image_tag "frontend/sections/selected_technologies/jq.png"
    li= image_tag "frontend/sections/selected_technologies/coffee.png"
    li= image_tag "frontend/sections/selected_technologies/bb.png"
    li= image_tag "frontend/sections/selected_technologies/h&c.png"
    li= image_tag "frontend/sections/selected_technologies/webgl.png"

app/views/frontend/sections/_selected_tools.html.slim
section#selected_tools.section-grey.show-for-medium-up
  ul.medium-block-grid-5.show-for-medium-only
    li= image_tag "frontend/sections/selected_tools/tool-jira.png"
    li= image_tag "frontend/sections/selected_tools/tool-github.png"
    li= image_tag "frontend/sections/selected_tools/tool-rails.png"
    li= image_tag "frontend/sections/selected_tools/tool-uxpin.png"
    li= image_tag "frontend/sections/selected_tools/tool-adobe.png"
  ul.large-block-grid-7.show-for-large-up
    li= image_tag "frontend/sections/selected_tools/tool-trello.png"
    li= image_tag "frontend/sections/selected_tools/tool-jira.png"
    li= image_tag "frontend/sections/selected_tools/tool-github.png"
    li= image_tag "frontend/sections/selected_tools/tool-rails.png"
    li= image_tag "frontend/sections/selected_tools/tool-uxpin.png"
    li= image_tag "frontend/sections/selected_tools/tool-adobe.png"
    li= image_tag "frontend/sections/selected_tools/tool-mandrill.png"

app/views/frontend/sections/_technologies.html.slim
section#technologies
  .row
    == section_heading "technologies"
    p== t "technologies", scope: "section_texts"
    .blocks.clearfix.p-t-80.p-b-40
      - 4.times do |b|
        .block.large-3.columns class="block-#{b+1}"
          .image
            = image_tag "frontend/sections/technologies/thumb-block#{b+1}.png"
          .section-heading
            h3
              == t "heading", scope: "technologies.block#{b+1}"
              span.border
          ul
            - technologies[b].each do |t|
              li= t

app/views/frontend/sections/_what_we_do.html.slim
section#what_we_do.p-t-110
  .row.m-b-40
    == section_heading "what_we_do"
    p== t "what_we_do", scope: "section_texts"
  .blocks.row
    - 4.times do |b|
      .block.large-3.columns class="block-#{b+1}"
        .image
          = image_tag "frontend/sections/what_we_do/thumb-block#{b+1}.png"
        .section-heading
          h3
            == t "heading", scope: "what_we_do_blocks.block#{b+1}"
            span.border
        p
          == t "text", scope: "what_we_do_blocks.block#{b+1}"

app/views/layouts/_bookmarks.html.slim
#bookmark-inner
  ul.bookmarks
    li
      a href="https://github.com/RSTgroup" target="_blank"
        = image_tag "frontend/sections/our_team/icon-github.png"
    li
      a href="/files/rst_our_cv.pdf" target="_blank"
        = image_tag "frontend/sections/our_team/icon-cv.png"
    li.red.hire-us
      a.to-section href="#hire_us" == t("hire_us", scope: "labels")

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div[class="alert-box #{name.to_s == 'notice' ? 'success' : 'alert'}" data-alert]
      = content_tag :div, msg
      a.close[href="#"]
        | ×

app/views/layouts/_navigation.html.slim
.row
  h1 RST IT
  a#logo href=root_path
    = image_tag "frontend/rst-logo.png"
  nav
    - if main_menu && main_menu.any?
      ul#main_menu
        - main_menu.each do |e|
          li.n
            a.to-section href="##{e}" = t(e, scope: "main_menu")
            
    ul#locale
      li class="#{'selected' if locale.to_s=='en'}"
        = link_to 'en', root_url(locale: 'en')
      li
        span= "/"
      li class="#{'selected' if locale.to_s=='de'}"
        = link_to 'de', root_url(locale: 'de')

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/frontend.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'RST-IT'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'RST IT'}"
    == stylesheet_link_tag "/fonts", :media => "all"
    == stylesheet_link_tag "frontend", :media => "all", "data-turbolinks-track" => true
    / Modernizr is required for Zurb Foundation
    == javascript_include_tag "vendor/modernizr"
    == javascript_include_tag "frontend", "data-turbolinks-track" => true
    == javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyDF1Xkip9BFkwz2ykfn1hsOJHOyONgU2Q0&sensor=false"
    == csrf_meta_tags
  body
    header#top_bar.normal.stycky
      == render 'layouts/navigation'
    #bookmarks
      == render 'layouts/bookmarks'
    #content
      == render 'layouts/messages'
      == yield
    footer
      #footer_blocks
        .row
          .block.large-2.columns.offer
            a href="/files/rst_offer.pdf" target="_blank"
              span.icon
                i.fc-pdf
              span.text== t "our_offer", scope: "footer_blocks"
          .block.large-2.columns.cv
            a href="/files/rst_our_cv.pdf" target="_blank"
              span.icon
                i.fc-cv
              span.text== t "sample_cv", scope: "footer_blocks"
          .block.large-4.columns.kmpit
            span.icon
              / i.fc-kmpit
              = image_tag "frontend/rst-logo-white.png"
          .block.large-2.columns.github
            a href="https://github.com/RSTgroup" target="_blank"  
              span.icon
                i.fc-octocat
              span.text== t "github", scope: "footer_blocks"
          .block.large-2.columns.linkedin
            a href="https://www.linkedin.com/company/kmp-group?report%2Esuccess=bvNSFZ6UfMPMO1h2mYYjQ-e1htOo_4zxkhy_sxeT5%2E%2E%2E" target="_blank"
              span.icon
                i.fc-linkedin
              span.text== t "linkedin", scope: "footer_blocks"
      #copy
        | Copyright RST-IT 2014
    javascript:
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-23324597-3', 'kmpit.com');
      ga('send', 'pageview');
    javascript:
      adroll_adv_id = "NLVCAKGLZZAYXB76H3UAJS";
      adroll_pix_id = "LBRW7Q3ODVEXXNV7AMLYF3";
      (function () {
      var oldonload = window.onload;
      window.onload = function(){
         __adroll_loaded=true;
         var scr = document.createElement("script");
         var host = (("https:" == document.location.protocol) ? "https://s.adroll.com" : "http://a.adroll.com");
         scr.setAttribute('async', 'true');
         scr.type = "text/javascript";
         scr.src = host + "/j/roundtrip.js";
         ((document.getElementsByTagName('head') || [null])[0] ||
          document.getElementsByTagName('script')[0].parentNode).appendChild(scr);
         if(oldonload){oldonload()}};
      }());
    erb: 
      <!-- Google Code for KMPIT.com -->
      <!-- Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. For instructions on adding this tag and more information on the above requirements, read the setup guide: google.com/ads/remarketingsetup -->
      <script type="text/javascript">
      /* <![CDATA[ */
      var google_conversion_id = 966460854;
      var google_conversion_label = "EBOECMrFnwgQtovszAM";
      var google_custom_params = window.google_tag_params;
      var google_remarketing_only = true;
      /* ]]> */
      </script>
      <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
      </script>
      <noscript>
      <div style="display:inline;">
      <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/966460854/?value=1.000000&amp;label=EBOECMrFnwgQtovszAM&amp;guid=ON&amp;script=0"/>
      </div>
      </noscript>